[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'


[[plugins]]
repo = 'vim-jp/vimdoc-ja'


[[plugins]]
repo = 'tyru/open-browser.vim'


[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.vim/userautoload/plugin/quickrun.vim'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'thinca/vim-template'


[[plugins]]
repo = 'junegunn/vim-easy-align'


[[plugins]]
repo = 'fuenor/JpFormat.vim'
hook_add = 'source ~/.vim/userautoload/plugin/jpformat.vim'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/userautoload/plugin/lightline.vim'


[[plugins]]
repo = 'fuenor/qfixgrep'


[[plugins]]
repo = 'fuenor/qfixhowm'
hook_add = 'source ~/.vim/userautoload/plugin/howm.vim'


[[plugins]]
repo = 'davidhalter/jedi-vim'
hook_add = 'source ~/.vim/userautoload/plugin/jedi.vim'


[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'


[[plugins]]
repo = 'cespare/vim-toml'



